In [53]:
import pandas as pd

df=pd.read_csv(r"C:\Users\iat\Downloads\environment_data.csv")

#will give top 10 rows
print(df.head(20))

#will give bottom 10 rows
print(df.tail(10))

    year              sector  class                              cfn_tle1  \
0   2009  Central government  Total  Environmental protection expenditure
1   2010  Central government  Total  Environmental protection expenditure
2   2011  Central government  Total  Environmental protection expenditure
3   2012  Central government  Total  Environmental protection expenditure
4   2013  Central government  Total  Environmental protection expenditure
5   2014  Central government  Total  Environmental protection expenditure
6   2015  Central government  Total  Environmental protection expenditure
7   2016  Central government  Total  Environmental protection expenditure
8   2017  Central government  Total  Environmental protection expenditure
9   2018  Central government  Total  Environmental protection expenditure
10  2019  Central government  Total  Environmental protection expenditure
11  2020  Central government  Total  Environmental protection expenditure
12  2021  Central government  Total  Environmental protection expenditure
13  2022  Central government  Total  Environmental protection expenditure
14  2009  Central government  Total  Environmental protection expenditure
15  2010  Central government  Total  Environmental protection expenditure
16  2011  Central government  Total  Environmental protection expenditure
17  2012  Central government  Total  Environmental protection expenditure
18  2013  Central government  Total  Environmental protection expenditure
19  2014  Central government  Total  Environmental protection expenditure

                         cfn_tle2       units magnitude  \
0   Final consumption expenditure  Proportion    Actual
1   Final consumption expenditure  Proportion    Actual
2   Final consumption expenditure  Proportion    Actual
3   Final consumption expenditure  Proportion    Actual
4   Final consumption expenditure  Proportion    Actual
5   Final consumption expenditure  Proportion    Actual
6   Final consumption expenditure  Proportion    Actual
7   Final consumption expenditure  Proportion    Actual
8   Final consumption expenditure  Proportion    Actual
9   Final consumption expenditure  Proportion    Actual
10  Final consumption expenditure  Proportion    Actual
11  Final consumption expenditure  Proportion    Actual
12  Final consumption expenditure  Proportion    Actual
13  Final consumption expenditure  Proportion    Actual
14  Final consumption expenditure     Dollars  Millions
15  Final consumption expenditure     Dollars  Millions
16  Final consumption expenditure     Dollars  Millions
17  Final consumption expenditure     Dollars  Millions
18  Final consumption expenditure     Dollars  Millions
19  Final consumption expenditure     Dollars  Millions

                    source  data_value flag
0   Environmental Accounts         1.2    F
1   Environmental Accounts         1.2    F
2   Environmental Accounts         1.1    F
3   Environmental Accounts         1.1    F
4   Environmental Accounts         1.2    F
5   Environmental Accounts         1.1    F
6   Environmental Accounts         1.2    F
7   Environmental Accounts         1.1    F
8   Environmental Accounts         1.2    F
9   Environmental Accounts         1.2    F
10  Environmental Accounts         1.1    F
11  Environmental Accounts         1.2    F
12  Environmental Accounts         1.2    P
13  Environmental Accounts         1.3    P
14  Environmental Accounts       408.0    F
15  Environmental Accounts       420.0    F
16  Environmental Accounts       399.0    F
17  Environmental Accounts       411.0    F
18  Environmental Accounts       438.0    F
19  Environmental Accounts       440.0    F
     year            sector       class                              cfn_tle1  \
482  2011  Local government  Wastewater  Environmental protection expenditure
483  2012  Local government  Wastewater  Environmental protection expenditure
484  2013  Local government  Wastewater  Environmental protection expenditure
485  2014  Local government  Wastewater  Environmental protection expenditure
486  2015  Local government  Wastewater  Environmental protection expenditure
487  2016  Local government  Wastewater  Environmental protection expenditure
488  2017  Local government  Wastewater  Environmental protection expenditure
489  2018  Local government  Wastewater  Environmental protection expenditure
490  2019  Local government  Wastewater  Environmental protection expenditure
491  2020  Local government  Wastewater  Environmental protection expenditure

                          cfn_tle2    units magnitude                  source  \
482  Gross fixed capital formation  Dollars  Millions  Environmental Accounts
483  Gross fixed capital formation  Dollars  Millions  Environmental Accounts
484  Gross fixed capital formation  Dollars  Millions  Environmental Accounts
485  Gross fixed capital formation  Dollars  Millions  Environmental Accounts
486  Gross fixed capital formation  Dollars  Millions  Environmental Accounts
487  Gross fixed capital formation  Dollars  Millions  Environmental Accounts
488  Gross fixed capital formation  Dollars  Millions  Environmental Accounts
489  Gross fixed capital formation  Dollars  Millions  Environmental Accounts
490  Gross fixed capital formation  Dollars  Millions  Environmental Accounts
491  Gross fixed capital formation  Dollars  Millions  Environmental Accounts

     data_value flag
482       334.0    F
483       510.0    F
484       744.0    F
485       685.0    F
486       839.0    F
487       714.0    F
488       700.0    F
489       683.0    F
490       780.0    F
491       824.0    F

In [50]:
#give the summary statistics of all statestics columns
print(df.describe())

#gives information about datatypes in dataset
print(df.info())

              year    data_value
count   492.000000    492.000000
mean   2015.012195   3627.312195
std       3.796753  11212.808490
min    2009.000000      0.000000
25%    2012.000000      2.900000
50%    2015.000000     33.000000
75%    2018.000000    879.250000
max    2022.000000  75659.000000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 492 entries, 0 to 491
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   year        492 non-null    int64
 1   sector      492 non-null    object
 2   class       492 non-null    object
 3   cfn_tle1    492 non-null    object
 4   cfn_tle2    492 non-null    object
 5   units       492 non-null    object
 6   magnitude   492 non-null    object
 7   source      492 non-null    object
 8   data_value  492 non-null    float64
 9   flag        492 non-null    object
dtypes: float64(1), int64(1), object(8)
memory usage: 38.6+ KB
None

In [49]:
#will get rows and columns
print(df.shape)

#will give only rows
print(df.shape[0])

#will give only colmns
print(df.shape[1])

print(df.columns)

(492, 10)
492
10
Index(['year', 'sector', 'class', 'cfn_tle1', 'cfn_tle2', 'units', 'magnitude',
       'source', 'data_value', 'flag'],
      dtype='object')

In [54]:
#To check the missing values

print(df.isnull().head(10))
print(df.isnull().sum())

    year  sector  class  cfn_tle1  cfn_tle2  units  magnitude  source  \
0  False   False  False     False     False  False      False   False
1  False   False  False     False     False  False      False   False
2  False   False  False     False     False  False      False   False
3  False   False  False     False     False  False      False   False
4  False   False  False     False     False  False      False   False
5  False   False  False     False     False  False      False   False
6  False   False  False     False     False  False      False   False
7  False   False  False     False     False  False      False   False
8  False   False  False     False     False  False      False   False
9  False   False  False     False     False  False      False   False

   data_value   flag
0       False  False
1       False  False
2       False  False
3       False  False
4       False  False
5       False  False
6       False  False
7       False  False
8       False  False
9       False  False
year          0
sector        0
class         0
cfn_tle1      0
cfn_tle2      0
units         0
magnitude     0
source        0
data_value    0
flag          0
dtype: int64

In [55]:
#slicing and extracting data

#to get one column data
print(df['year'].head(10))

#to get more than one column data
print(df[['year','class']].head(15))

#will get the data at a specific index
print(df[df.index==21])

0    2009
1    2010
2    2011
3    2012
4    2013
5    2014
6    2015
7    2016
8    2017
9    2018
Name: year, dtype: int64
    year  class
0   2009  Total
1   2010  Total
2   2011  Total
3   2012  Total
4   2013  Total
5   2014  Total
6   2015  Total
7   2016  Total
8   2017  Total
9   2018  Total
10  2019  Total
11  2020  Total
12  2021  Total
13  2022  Total
14  2009  Total
    year              sector  class                              cfn_tle1  \
21  2016  Central government  Total  Environmental protection expenditure

                         cfn_tle2    units magnitude                  source  \
21  Final consumption expenditure  Dollars  Millions  Environmental Accounts

    data_value flag
21       457.0    F

In [56]:
df.head(20)

#will get data at a specific index
print(df.loc[8])
print(df.iloc[8])

#if we use iloc,we will get the data from 15-20 rows(n-1 will apply)
print(df.iloc[15:21])
#if we use loc,we will get the data from 15-21 rows
print(df.loc[15:21])

year                                          2017
sector                          Central government
class                                        Total
cfn_tle1      Environmental protection expenditure
cfn_tle2             Final consumption expenditure
units                                   Proportion
magnitude                                   Actual
source                      Environmental Accounts
data_value                                     1.2
flag                                             F
Name: 8, dtype: object
year                                          2017
sector                          Central government
class                                        Total
cfn_tle1      Environmental protection expenditure
cfn_tle2             Final consumption expenditure
units                                   Proportion
magnitude                                   Actual
source                      Environmental Accounts
data_value                                     1.2
flag                                             F
Name: 8, dtype: object
    year              sector  class                              cfn_tle1  \
15  2010  Central government  Total  Environmental protection expenditure
16  2011  Central government  Total  Environmental protection expenditure
17  2012  Central government  Total  Environmental protection expenditure
18  2013  Central government  Total  Environmental protection expenditure
19  2014  Central government  Total  Environmental protection expenditure
20  2015  Central government  Total  Environmental protection expenditure

                         cfn_tle2    units magnitude                  source  \
15  Final consumption expenditure  Dollars  Millions  Environmental Accounts
16  Final consumption expenditure  Dollars  Millions  Environmental Accounts
17  Final consumption expenditure  Dollars  Millions  Environmental Accounts
18  Final consumption expenditure  Dollars  Millions  Environmental Accounts
19  Final consumption expenditure  Dollars  Millions  Environmental Accounts
20  Final consumption expenditure  Dollars  Millions  Environmental Accounts

    data_value flag
15       420.0    F
16       399.0    F
17       411.0    F
18       438.0    F
19       440.0    F
20       465.0    F
    year              sector  class                              cfn_tle1  \
15  2010  Central government  Total  Environmental protection expenditure
16  2011  Central government  Total  Environmental protection expenditure
17  2012  Central government  Total  Environmental protection expenditure
18  2013  Central government  Total  Environmental protection expenditure
19  2014  Central government  Total  Environmental protection expenditure
20  2015  Central government  Total  Environmental protection expenditure
21  2016  Central government  Total  Environmental protection expenditure

                         cfn_tle2    units magnitude                  source  \
15  Final consumption expenditure  Dollars  Millions  Environmental Accounts
16  Final consumption expenditure  Dollars  Millions  Environmental Accounts
17  Final consumption expenditure  Dollars  Millions  Environmental Accounts
18  Final consumption expenditure  Dollars  Millions  Environmental Accounts
19  Final consumption expenditure  Dollars  Millions  Environmental Accounts
20  Final consumption expenditure  Dollars  Millions  Environmental Accounts
21  Final consumption expenditure  Dollars  Millions  Environmental Accounts

    data_value flag
15       420.0    F
16       399.0    F
17       411.0    F
18       438.0    F
19       440.0    F
20       465.0    F
21       457.0    F

In [60]:
#dealing with missing data

#1.Dropping missing values
data1=df.dropna()
print(data1.isnull().sum())

#2.Replacing missing values(mean,median)
mean_value=df['data_value'].mean()
print(f"mean_value:{mean_value}")

median_value=df['data_value'].median()
print(f"median_value:{median_value}")
df.fillna(median_value)
df.head(10)

#Renaming column
print(df.rename(columns={'year':'YEAR'},inplace=True))
df.head(10)

YEAR          0
sector        0
class         0
cfn_tle1      0
cfn_tle2      0
units         0
magnitude     0
source        0
data_value    0
flag          0
dtype: int64
mean_value:3627.312195121951
median_value:33.0
None

,YEAR,sector,class,cfn_tle1,cfn_tle2,units,magnitude,source,data_value,flag
0,2009,Central government,Total,Environmental protection expenditure,Final consumption expenditure,Proportion,Actual,Environmental Accounts,1.2,F
1,2010,Central government,Total,Environmental protection expenditure,Final consumption expenditure,Proportion,Actual,Environmental Accounts,1.2,F
2,2011,Central government,Total,Environmental protection expenditure,Final consumption expenditure,Proportion,Actual,Environmental Accounts,1.1,F
3,2012,Central government,Total,Environmental protection expenditure,Final consumption expenditure,Proportion,Actual,Environmental Accounts,1.1,F
4,2013,Central government,Total,Environmental protection expenditure,Final consumption expenditure,Proportion,Actual,Environmental Accounts,1.2,F
5,2014,Central government,Total,Environmental protection expenditure,Final consumption expenditure,Proportion,Actual,Environmental Accounts,1.1,F
6,2015,Central government,Total,Environmental protection expenditure,Final consumption expenditure,Proportion,Actual,Environmental Accounts,1.2,F
7,2016,Central government,Total,Environmental protection expenditure,Final consumption expenditure,Proportion,Actual,Environmental Accounts,1.1,F
8,2017,Central government,Total,Environmental protection expenditure,Final consumption expenditure,Proportion,Actual,Environmental Accounts,1.2,F
9,2018,Central government,Total,Environmental protection expenditure,Final consumption expenditure,Proportion,Actual,Environmental Accounts,1.2,F

In [57]:
#value_count

print(df['flag'].value_counts())

flag
F    419
R     37
P     36
Name: count, dtype: int64